packages:
  - "apps/*"
  - "examples/basic-traces/typescript"
  - "examples/openinference-openai/typescript"
  - "packages/*"

reporter: silent

allowBuilds:
  esbuild: true
  protobufjs: true

minimumReleaseAgeExclude:
  - '@duckdb/node-api@1.5.4-r.1'
  - '@duckdb/node-bindings-darwin-arm64@1.5.4-r.1'
  - '@duckdb/node-bindings-darwin-x64@1.5.4-r.1'
  - '@duckdb/node-bindings-linux-arm64-musl@1.5.4-r.1'
  - '@duckdb/node-bindings-linux-arm64@1.5.4-r.1'
  - '@duckdb/node-bindings-linux-x64-musl@1.5.4-r.1'
  - '@duckdb/node-bindings-linux-x64@1.5.4-r.1'
  - '@duckdb/node-bindings-win32-arm64@1.5.4-r.1'
  - '@duckdb/node-bindings-win32-x64@1.5.4-r.1'
  - '@duckdb/node-bindings@1.5.4-r.1'
  - uuid@11.1.1

overrides:
  uuid@<11.1.1: ^11.1.1
