packages:
  - "apps/*"
  - "examples/basic-traces/typescript"
  - "examples/openinference-openai/typescript"
  - "packages/*"

reporter: silent
autoInstallPeers: false

minimumReleaseAge: 10080
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3

allowBuilds:
  esbuild: true
  protobufjs: true

minimumReleaseAgeExclude:
  - '@opentelemetry/*'
  - '@duckdb/node-api@1.5.4-r.1'
  - '@duckdb/node-bindings-darwin-arm64@1.5.4-r.1'
  - '@duckdb/node-bindings-darwin-x64@1.5.4-r.1'
  - '@duckdb/node-bindings-linux-arm64-musl@1.5.4-r.1'
  - '@duckdb/node-bindings-linux-arm64@1.5.4-r.1'
  - '@duckdb/node-bindings-linux-x64-musl@1.5.4-r.1'
  - '@duckdb/node-bindings-linux-x64@1.5.4-r.1'
  - '@duckdb/node-bindings-win32-arm64@1.5.4-r.1'
  - '@duckdb/node-bindings-win32-x64@1.5.4-r.1'
  - '@duckdb/node-bindings@1.5.4-r.1'
  - uuid@11.1.1

overrides:
  '@opentelemetry/core': ^2.9.0
  uuid@<11.1.1: ^11.1.1
